# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# In order for SonarQube (Server or Cloud) analysis to succeed you need to disable the fetch debt.
# Please check Disable shallow fetch topic in the following link:
# https://dev.to/kkazala/azure-devops-pipelines-shallow-fetch-1-is-now-default-4656

trigger:
    paths:
        include:
            - 'sonar-scanner-gradle/gradle-basic/*'

pool:
  vmImage: ubuntu-latest

steps:


- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'  # Path to your Gradle wrapper
    tasks: 'build'  # Replace with the tasks you want to run
    options: '-Xmx3072m' 
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'  # Updated pattern for test result files
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'  # Replace with your JDK version
    jdkArchitectureOption: 'x64'
