# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# In order for SonarQube (Server or Cloud) analysis to succeed you need to disable the fetch debt.
# Please check Disable shallow fetch topic in the following link:
# https://dev.to/kkazala/azure-devops-pipelines-shallow-fetch-1-is-now-default-4656

trigger:
    paths:
        include:
            - 'sonar-scanner-gradle/gradle-basic/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarQube Cloud Production'
    organization: 'azure-devops-onboarding-examples'
    scannerMode: 'other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.verbose=true
      sonar.projectKey=onboarding-examples_gradle-basic
      sonar.projectName=Onboarding Example - AzureDevOps - Gradle Example

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'sonar-scanner-gradle/gradle-basic/gradlew'
    workingDirectory: 'sonar-scanner-gradle/gradle-basic/'
    options: '-i -d'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '5.1.0.4882'
    spotBugsAnalysis: false
