# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
    paths:
        include:
            - 'sonar-scanner-gradle/gradle-basic/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube Server'
    scannerMode: 'other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.verbose=true
      sonar.projectKey=onboarding-examples_gradle-basic
      sonar.projectName=Onboarding Example - AzureDevOps - Gradle Example
        include:
            - 'sonar-scanner-gradle/gradle-basic/*'
            
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'sonar-scanner-gradle/gradle-basic/gradlew'
    workingDirectory: 'sonar-scanner-gradle/gradle-basic/'
    options: '-i'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '5.1.0.4882'
    spotBugsAnalysis: falsegradlew'